environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  #- TARGET: i686-pc-windows-gnu
install:
  - appveyor DownloadFile "https://static.rust-lang.org/dist/rust-nightly-%TARGET%.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Rust"
  - SET PATH=%PATH%;C:\Rust\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  #- link.exe -help
  - rustc -vV
  - cargo -vV
  - git submodule update --init --recursive
build_script:
  - cd C:\projects\wtl-rs\tools\ui_gen
  - cargo build
test_script:
  - cd C:\projects\wtl-rs\
  - cargo test