environment:
  matrix:
  - TARGET: x86_64-pc-windows-gnu
  - TARGET: i686-pc-windows-gnu
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -vV
  - cargo -vV
  - git submodule update --init --recursive
build_script:
  - cd C:\projects\wtl-rs\examples\hello_dialog
  - cargo build
test_script:
  - cd C:\projects\wtl-rs\
  - cargo test